project:
  id: MRS_MB_META_TECH
  name: MRS MB Meta Technical
  description: Reviewer notebook technical-validation-only run
  owner: local
data:
  train:
    manifest: /Users/alex/Documents/project-MLSubtype/data/MBmerged-z-scores_MLready_correction.csv
key_columns:
  label: MOLECULAR
task:
  mode: meta
  patient_stratified: false
validation:
  nested_cv:
    outer_folds: 3
    inner_folds: 3
    repeats: 1
    seed: 42
models:
  candidates:
  - logistic_regression
  - svm
  - random_forest
  selection_metric: f1
  selection_direction: max
imbalance:
  smote:
    enabled: false
    compare: false
multiclass:
  group_stratify: true
  sklearn:
    logreg:
      solver: saga
      multi_class: auto
      penalty: l2
      max_iter: 5000
      tol: 0.001
      C: 1.0
      class_weight: balanced
      n_jobs: -1
metrics:
  primary:
  - f1
  - balanced_accuracy
  averaging: macro
  include_confidence_intervals: false
calibration:
  enabled: 'true'
  method: sigmoid
  cv: 3
  bins: 10
  binning: uniform
  isotonic_min_samples: 100
  policy:
    apply_to_modes:
    - meta
    force_keep: false
    thresholds:
      underconfidence_gap: -0.1
      high_accuracy: 0.9
      near_perfect_accuracy: 0.97
      min_calibration_n: 200
      min_class_n: 25
      min_brier_improvement: 0.002
      max_log_loss_regression: 0.01
      max_ece_ovr_regression: 0.01
final_model:
  sanity_min_std: 0.02
  sanity_max_mean_deviation: 0.15
  train_from_scratch: true
  verify_dataset_hash: true
bundle:
  name: model_bundle
  include_preprocessing: true
  format: zip
execution:
  engine: sklearn
