project:
  id: CNS_FAMILY_C
  name: CNS_FAMILY_CLASSIFLOW
  description: ''
  owner: ''
data:
  train:
    manifest: /home/sagemaker-user/data/classiflow_data/CNS_FULL_DATASET_FAMILY_TRAIN.parquet
  test:
    manifest: /home/sagemaker-user/data/classiflow_data/CNS_FULL_DATASET_FAMILY_TEST.parquet
key_columns:
  sample_id: sample_id
  label: label
task:
  mode: multiclass
  patient_stratified: true
validation:
  nested_cv:
    outer_folds: 3
    inner_folds: 5
    repeats: 2
    seed: 42
models:
  candidates:
  - torch_logistic_regression
  - torch_mlp
  selection_metric: f1
  selection_direction: max
imbalance:
  smote:
    enabled: false
    compare: false
metrics:
  primary:
  - f1
  - balanced_accuracy
  averaging: macro
  include_confidence_intervals: false
final_model:
  sanity_min_std: 0.02
  sanity_max_mean_deviation: 0.15
  train_from_scratch: true
  verify_dataset_hash: true
bundle:
  name: model_bundle
  include_preprocessing: true
  format: zip
execution:
  engine: torch
  device: cuda
  torch:
    dtype: float32
    num_workers: 30
    require_device: false
multiclass:
  group_stratify: true
  backend: torch_cuda
  sklearn:
    logreg:
      solver: saga
      multi_class: auto
      penalty: l2
      max_iter: 5000
      tol: 0.001
      C: 1.0
      class_weight: balanced
      n_jobs: -1
  torch:
    model_set: torch_basic

# Common knobs to edit:
# - key_columns.label / key_columns.patient_id
# - models.candidates, models.selection_metric
# - validation.nested_cv.outer_folds / inner_folds / repeats
# - multiclass.backend and multiclass.sklearn.logreg.*
# - execution.device and execution.torch.*
# Advanced knobs: execution.model_set, execution.torch.num_workers
